package aplicacion_1;
import javax.swing.JOptionPane;
/**
 *
 * @author Walter Dario Maza Cuadrado
 */ 
public class Inicio_1 extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inicio_1.class.getName());
    /**
     * Creates new form Inicio
     */
    private static Inicio_configuracion config;
    private static Inicio_1 instancia;
    public Inicio_1(Inicio_configuracion config) {
        initComponents();
        this.config = config;
        ThemeManager.aplicarTema(this); //aplicamos también a este JFrame cuando se configuren los colores
        setLocationRelativeTo(null);        // centramos el JFrame
    }
   public static Inicio_1 getInstance(Inicio_configuracion config) {
         if (instancia == null) {                          // esta función permite obtener una instancia a partir del JFrame principal
            instancia = new Inicio_1(config);              // si no existe ninguna, se crea
        }
        else {                    
        instancia.toFront();                 //en cambio, si ya existe una ventana al menos, se enfoca esta misma al frente
        instancia.requestFocus(); }          // y no se abren más, permitiendo que sea más organizado
         return instancia;
     }
    @Override  //se sobreescribe para que pueda ser posible que solo exista una instancia por más clicks
    public void dispose() {
        super.dispose();
        instancia = null;
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_iniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_cuenta = new javax.swing.JTextField();
        txt_contra = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bodega El Olivar - Iniciar sesión");
        setBackground(new java.awt.Color(51, 153, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setForeground(new java.awt.Color(242, 242, 242));
        setMinimumSize(new java.awt.Dimension(394, 192));
        setResizable(false);
        setSize(new java.awt.Dimension(418, 208));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_iniciar.setBackground(new java.awt.Color(0, 153, 0));
        btn_iniciar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_iniciar.setForeground(new java.awt.Color(204, 255, 204));
        btn_iniciar.setText("Iniciar sesión");
        btn_iniciar.setToolTipText("");
        btn_iniciar.setFocusPainted(false);
        btn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 150, 160, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("Contraseña:");
        jLabel1.setAutoscrolls(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 108, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("¡Bienvenido a El Olivar, tu bodega local que está cerca de ti!"); // NOI18N
        jLabel2.setAutoscrolls(true);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Para empezar, inicie sesión con su respectiva cuenta.");
        jLabel3.setAutoscrolls(true);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 20));

        txt_cuenta.setBackground(new java.awt.Color(204, 255, 204));
        txt_cuenta.setForeground(new java.awt.Color(0, 102, 51));
        txt_cuenta.setToolTipText("");
        txt_cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cuentaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_cuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 83, 220, -1));

        txt_contra.setBackground(new java.awt.Color(204, 255, 204));
        txt_contra.setForeground(new java.awt.Color(0, 102, 51));
        txt_contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contraActionPerformed(evt);
            }
        });
        getContentPane().add(txt_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 110, 220, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("Nombre de la cuenta:");
        jLabel5.setAutoscrolls(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 83, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 153, 51));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setAutoscrolls(true);
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 470, 220));

        setSize(new java.awt.Dimension(416, 231));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarActionPerformed
        String usuario = txt_cuenta.getText(); String contraseña = txt_contra.getText();
        if (bsd_usuarios.login(usuario, contraseña))  // comprobamos información del usuario ingresado
        {
            bsd_inventario.inicializar_sql(); //se cargarán TODOS los datos, sean nuevos o actualizados
            JOptionPane.showMessageDialog(null, "¡Bienvenido, " + usuario + "!");
            Inicio_principal prin = new Inicio_principal();
            prin.setSize(775, 547);
            prin.setVisible(true);
            dispose();
        }
        else {
            txt_cuenta.setText("");
            txt_contra.setText("");
            JOptionPane.showMessageDialog(null, "No se registra ningún usuario y/o contraseña en el sistema.\nPor favor, ingrese un usuario y/o contraseña válidos.", 
                    "Usuario inválido", JOptionPane.WARNING_MESSAGE); }
    }//GEN-LAST:event_btn_iniciarActionPerformed

    private void txt_cuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cuentaActionPerformed

    private void txt_contraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contraActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    int opcion = JOptionPane.showConfirmDialog(null, "¿Seguro que deseas salir de la aplicación", 
            "Salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    if (opcion == JOptionPane.YES_OPTION) {
        System.exit(0); //Se utiliza para cerrar por completo la aplicación
    }        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Inicio_1(config).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txt_contra;
    private javax.swing.JTextField txt_cuenta;
    // End of variables declaration//GEN-END:variables
}
