package aplicacion_1;
import java.sql.*; // todas las librerias de SQL para Java
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import java.util.Date;
/**
 *
 * @author Walter Dario Maza Cuadrado
 */
public class JF_Fiados extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JF_Fiados.class.getName());
    /**
     * Creates new form JF_Fiados
     */
    private static Inicio_principal inicio;
    public JTable tabla() { return tabla_cmp; } //el valor de la tabla 
                                                 //para cual sus colores se configuran en Inicio_configuracion
    private static JF_Fiados instancia;  //esto estará en todo JFrame excepto el principal y el login, para crear únicas instancias
    public JF_Fiados(Inicio_principal jf_pr) {
        initComponents();
        this.inicio = jf_pr;  //creamos la instancia
        ThemeManager.aplicarTema(this);  // se carga el tema (vease el JFrame Inicio_configuracion)
        bsd_inventario.aplicarRenderer(tabla_cmp);  // y también a la tabla (vease el JFrame Inicio_configuracion)
        setLocationRelativeTo(null);      // centramos el JFrame 
        
        cc_productos.removeAllItems(); 
        bsd_inventario.carga_productos_TR(cc_productos);
        bsd_inventario.actualizacion_productos_TR(cc_productos, txtMonto);
        DefaultTableModel modelo = (DefaultTableModel) tabla_cmp.getModel();
        tabla_cmp.setModel(bsd_inventario.load_fiados_sql(modelo)); //cargamos los clientes con cuentas por pagar
    }
    public static JF_Fiados getInstance(Inicio_principal jf_pr) {
         if (instancia == null) {                          // esta función permite obtener una instancia a partir del JFrame principal
            instancia = new JF_Fiados(jf_pr);              // si no existe ninguna, se crea
        }
        else {                    
        instancia.toFront();                 //en cambio, si ya existe una ventana al menos, se enfoca esta misma al frente
        instancia.requestFocus(); }          // y no se abren más, permitiendo que sea más organizado
         return instancia;
     }
    @Override  //se sobreescribe para que pueda ser posible que solo exista una instancia por más clicks
    public void dispose() {
        super.dispose();
        instancia = null;
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        scrll_tabla = new javax.swing.JScrollPane();
        tabla_cmp = new javax.swing.JTable();
        cc_productos = new javax.swing.JComboBox<>();
        btnagregar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        lnl_fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Módulo de fiados - Bodega El Olivar");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 153, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Registro de clientes fiados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 255, 204))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(204, 255, 204));
        jPanel1.setToolTipText("");
        jPanel1.setFocusable(false);
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("Monto (S/.):");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 75, 80, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("Producto:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 70, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("Cliente:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 35, 60, -1));

        txtCliente.setBackground(new java.awt.Color(204, 255, 204));
        txtCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCliente.setForeground(new java.awt.Color(0, 102, 51));
        txtCliente.setToolTipText("");
        jPanel1.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 750, -1));

        txtMonto.setBackground(new java.awt.Color(204, 255, 204));
        txtMonto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMonto.setForeground(new java.awt.Color(0, 102, 51));
        txtMonto.setToolTipText("");
        txtMonto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMonto.setEnabled(false);
        jPanel1.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 130, -1));

        scrll_tabla.setBackground(new java.awt.Color(204, 255, 204));
        scrll_tabla.setForeground(new java.awt.Color(0, 102, 51));
        scrll_tabla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        scrll_tabla.setRowHeaderView(null);

        tabla_cmp.setAutoCreateRowSorter(true);
        tabla_cmp.setBackground(new java.awt.Color(204, 255, 204));
        tabla_cmp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabla_cmp.setForeground(new java.awt.Color(0, 102, 51));
        tabla_cmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Producto", "Monto", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_cmp.setFocusable(false);
        tabla_cmp.setGridColor(new java.awt.Color(0, 204, 51));
        tabla_cmp.setInheritsPopupMenu(true);
        tabla_cmp.setSelectionBackground(new java.awt.Color(51, 153, 0));
        tabla_cmp.setSelectionForeground(new java.awt.Color(204, 255, 204));
        tabla_cmp.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabla_cmp.setShowGrid(true);
        scrll_tabla.setViewportView(tabla_cmp);

        jPanel1.add(scrll_tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 800, 240));

        cc_productos.setBackground(new java.awt.Color(0, 153, 0));
        cc_productos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cc_productos.setForeground(new java.awt.Color(204, 255, 204));
        cc_productos.setToolTipText("");
        cc_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cc_productosActionPerformed(evt);
            }
        });
        jPanel1.add(cc_productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 300, 30));

        btnagregar.setBackground(new java.awt.Color(0, 153, 0));
        btnagregar.setForeground(new java.awt.Color(204, 255, 204));
        btnagregar.setText("Agregar");
        btnagregar.setFocusPainted(false);
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 140, 40));

        btneliminar.setBackground(new java.awt.Color(0, 153, 0));
        btneliminar.setForeground(new java.awt.Color(204, 255, 204));
        btneliminar.setText("Eliminar");
        btneliminar.setFocusPainted(false);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 850, 410));

        lnl_fondo1.setBackground(new java.awt.Color(51, 153, 0));
        lnl_fondo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnl_fondo1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lnl_fondo1.setFocusCycleRoot(true);
        lnl_fondo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lnl_fondo1.setIconTextGap(2);
        lnl_fondo1.setOpaque(true);
        getContentPane().add(lnl_fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 900, 450));

        setSize(new java.awt.Dimension(905, 448));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        try {
        DefaultTableModel modelo = (DefaultTableModel) tabla_cmp.getModel();
        String cliente = txtCliente.getText();
        double monto = Double.parseDouble(txtMonto.getText());   //obtenemos los datos brindados del fiado
        String producto = cc_productos.getSelectedItem().toString();
        java.text.SimpleDateFormat formatoHora = new java.text.SimpleDateFormat("HH:mm:ss"); //hora y fecha del ingreso del fiado
        java.text.SimpleDateFormat formatoFecha = new java.text.SimpleDateFormat("dd/MM/yyyy");
        Date fecha_hoy_hora = new java.util.Date();     
        String fecha = formatoHora.format(fecha_hoy_hora) + " " + formatoFecha.format(fecha_hoy_hora);  
        //ahora lo agregamos a la fila  
        if (cliente.equals("")) {
            JOptionPane.showMessageDialog(this, "Debe completar el campo 'Cliente'.", "Error", JOptionPane.ERROR_MESSAGE); return;
        }
        else if (cliente.matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(this, "Ingrese un nombre de cliente válido. No debe incluir números'.", "Error", JOptionPane.ERROR_MESSAGE); return;
        }
        int id = modelo.getRowCount() + 1;
        bsd_inventario.agregarFiado(cliente, producto, monto, fecha);
        Object[] fila = {id, cliente, producto, monto, fecha};
        modelo.addRow(fila);
        //Mensaje de confirmación 
        JOptionPane.showMessageDialog(this, "Cliente agregado correctamente.", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {JOptionPane.showMessageDialog(this, "Error al agregar un cliente fiado.\n Verifique bien los campos de texto.", "Advertencia", JOptionPane.WARNING_MESSAGE);}
        cc_productos.repaint();
        cc_productos.revalidate();
    }//GEN-LAST:event_btnagregarActionPerformed
    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        try {
            DefaultTableModel modelo = (DefaultTableModel) tabla_cmp.getModel();
            int f_sec = tabla_cmp.getSelectedRow();  //la fila seleccionada a donde eliminaremos
            if (f_sec != -1) {
            int id = (Integer) modelo.getValueAt(f_sec, 0);
            String cliente = (String) modelo.getValueAt(f_sec, 1);
            bsd_inventario.eliminarFiado(id, cliente); // el procedimiento realizará la eliminación del cliente y su producto fiado
            modelo.removeRow(f_sec);
            } else throw new Exception("No existe ningún valor");
        } catch (Exception e) {JOptionPane.showMessageDialog(this, "Error al eliminar un cliente fiado.\nNo ha seleccionado una fila o no ha agregado ningún cliente fiado.", "Advertencia", JOptionPane.WARNING_MESSAGE);}
    }//GEN-LAST:event_btneliminarActionPerformed
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void cc_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cc_productosActionPerformed
        bsd_inventario.actualizacion_productos_TR(cc_productos, txtMonto);
    }//GEN-LAST:event_cc_productosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JF_Fiados(inicio).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JComboBox<String> cc_productos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lnl_fondo1;
    private javax.swing.JScrollPane scrll_tabla;
    private javax.swing.JTable tabla_cmp;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
