package aplicacion_1;
import java.sql.*; //importación de SQL para la base de datos
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
/**
 *
 * @author Walter Dario Maza Cuadrado
 */
public class JF_Stock extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JF_Stock.class.getName());
    /**
     * Creates new form JF_Fiados
     */
    private static Inicio_principal inicio;
   public JTable tabla() { return tabla_p; } //el valor de la tabla 
                                                 //para cual sus colores se configuran en Inicio_configuracion
    private static JF_Stock instancia;  //esto estará en todo JFrame excepto el principal y el login, para crear únicas instancias
    public static String cambio_fechayhora() {  //cambio a tiempo real
    java.time.LocalDateTime ahora = java.time.LocalDateTime.now();
    java.time.format.DateTimeFormatter formato =     //visualización de cada cambio a tiempo real de la tabla
            java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"); //con un formato bonito
    return ahora.format(formato);
}
    public JF_Stock(Inicio_principal jf_pr) {
        initComponents();        
        this.inicio = jf_pr;
        ThemeManager.aplicarTema(this);  // se carga el tema (vease el JFrame Inicio_configuracion)
        bsd_inventario.aplicarRenderer(tabla_p);  // y también a la tabla (vease el JFrame Inicio_configuracion)
        setLocationRelativeTo(null);      // centramos el JFrame 
        DefaultTableModel modelo = (DefaultTableModel) tabla_p.getModel();   //tabla del stock (exclusiva a este JFrame)
        boolean en_sql = false;
        try (Connection con = bsd_usuarios.conexion()) { // Asegúrate de tener los imports de java.sql
            if (con != null) {
                String sql = "SELECT Nombre, Stock, Fecha FROM Productos ORDER BY Nombre ASC";
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();                 //importamos los productos
                while (rs.next()) {
                    String nombre = rs.getString("Nombre");
                    int stock = rs.getInt("Stock");
                    String estado = bsd_inventario.indicador_stock(nombre, stock);
                    String fecha = rs.getString("Fecha");
                    modelo.addRow(new Object[]{nombre, stock, estado, fecha}); 
                }
                en_sql = true;
                System.out.println("Stock cargado correctamente.");
            }
        } catch (Throwable e) {
            System.out.println("⚠️ Error al cargar Stock en SQL: " + e.getMessage());
        }  
       modelo.addTableModelListener(e -> {    //un listener que acciona cada cambio del stock a tiempo real
           int f = e.getFirstRow(), c = e.getColumn();  //obtención de los valores de las columnas
           if (c == 1) {
               try {
               String producto = (String) modelo.getValueAt(f, 0);  //se obtienen las variables desde las columna cantidad
               int n_cantidad = Integer.parseInt(modelo.getValueAt(f, 1).toString());
               String n_estado = bsd_inventario.indicador_stock(producto, n_cantidad); //actualizamos el indicador dependiendo si hay o no cambios
               modelo.setValueAt(n_estado, f, 2); // y a partir de ello, lo vuelve a colocar
               modelo.setValueAt(cambio_fechayhora(), f, 3); // también la fecha en ese instante              
               bsd_inventario.upload_stock_sql(modelo, producto, n_cantidad, cambio_fechayhora()); //a SQL también 
               } catch (NumberFormatException n) 
               { System.out.println("Error. El valor ingresado no es un número. No se reemplazará en la base de datos.");
                 JOptionPane.showMessageDialog(this, "Cantidad inválida. Verifique si ingresó un número.");
               }
    } });
    }
    public static JF_Stock getInstance(Inicio_principal jf_pr) {
         if (instancia == null) {                            // esta función permite obtener una instancia a partir del JFrame principal
            instancia = new JF_Stock(jf_pr);                 // si no existe ninguna, se crea
        }
        else {                                        //en cambio, si ya existe una ventana al menos, se enfoca esta misma al frente
        instancia.toFront();                          // y no se abren más, permitiendo que sea más organizado
        instancia.requestFocus(); }
         return instancia;
     }
    @Override  //se sobreescribe para que pueda ser posible que solo exista una instancia por más clicks
    public void dispose() {
        super.dispose();
        instancia = null;
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrll_tabla = new javax.swing.JScrollPane();
        tabla_p = new javax.swing.JTable();
        lnl_fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Módulo de Stock - Bodega El Olivar");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 153, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Verificación del Stock", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 255, 204))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(204, 255, 204));
        jPanel1.setToolTipText("");
        jPanel1.setFocusable(false);
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrll_tabla.setBackground(new java.awt.Color(204, 255, 204));
        scrll_tabla.setForeground(new java.awt.Color(0, 102, 51));
        scrll_tabla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        scrll_tabla.setRowHeaderView(null);

        tabla_p.setAutoCreateRowSorter(true);
        tabla_p.setBackground(new java.awt.Color(204, 255, 204));
        tabla_p.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabla_p.setForeground(new java.awt.Color(0, 102, 51));
        tabla_p.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Disponibilidad", "Último cambio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_p.setFocusable(false);
        tabla_p.setGridColor(new java.awt.Color(0, 204, 51));
        tabla_p.setInheritsPopupMenu(true);
        tabla_p.setSelectionBackground(new java.awt.Color(51, 153, 0));
        tabla_p.setSelectionForeground(new java.awt.Color(204, 255, 204));
        tabla_p.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabla_p.setShowGrid(true);
        scrll_tabla.setViewportView(tabla_p);

        jPanel1.add(scrll_tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 810, 410));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 850, 460));

        lnl_fondo1.setBackground(new java.awt.Color(51, 153, 0));
        lnl_fondo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnl_fondo1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lnl_fondo1.setFocusCycleRoot(true);
        lnl_fondo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lnl_fondo1.setIconTextGap(2);
        lnl_fondo1.setOpaque(true);
        getContentPane().add(lnl_fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 900, 550));

        setSize(new java.awt.Dimension(887, 493));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JF_Stock(inicio).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lnl_fondo1;
    private javax.swing.JScrollPane scrll_tabla;
    private javax.swing.JTable tabla_p;
    // End of variables declaration//GEN-END:variables
}
