package aplicacion_1;
import java.sql.*; // importación de SQL para la base de datos
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Walter Dario Maza Cuadrado
 */
public final class JF_Ventas extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JF_Ventas.class.getName());
    /**
     * Creates new form JF_Ventas
     */
    private static Inicio_principal inicio;
    public JTable tabla() { return tabla_p; } //el valor de la tabla 
                                                 //para cual sus colores se configuran en Inicio_configuracion
    private static JF_Ventas instancia;  //esto estará en todo JFrame excepto el principal y el login, para crear únicas instancias
    public JF_Ventas(Inicio_principal jf_pr) {
        initComponents();
        this.inicio = jf_pr;
        ThemeManager.aplicarTema(this);  // se carga el tema (vease el JFrame Inicio_configuracion)
        bsd_inventario.aplicarRenderer(tabla_p);  // y también a la tabla (vease el JFrame Inicio_configuracion)
        setLocationRelativeTo(null);      // centramos el JFrame   
        bsd_inventario.carga_productos_TR(cc_productos);
        cc_productos.addActionListener(e -> bsd_inventario.actualizacion_productos_TR(cc_productos, txtPrecio));
        tabla_p.getModel().addTableModelListener(f -> sumarxcolumna());         
        DefaultTableModel modelo = (DefaultTableModel) tabla_p.getModel();
        modelo.setRowCount(0);  //reiniciamos el conteo de filas a 0 
                }
    public static JF_Ventas getInstance(Inicio_principal jf_pr) {
         if (instancia == null) {                            // esta función permite obtener una instancia a partir del JFrame principal
            instancia = new JF_Ventas(jf_pr);                // si no existe ninguna, se crea
        }
        else {
        instancia.toFront();                          //en cambio, si ya existe una ventana al menos, se enfoca esta misma al frente
        instancia.requestFocus(); }                  // y no se abren más, permitiendo que sea más organizado
         return instancia;
     }
    @Override  //se sobreescribe para que pueda ser posible que solo exista una instancia por más clicks
    public void dispose() {
        super.dispose();
        instancia = null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrll_tabla1 = new javax.swing.JScrollPane();
        tabla_p = new javax.swing.JTable();
        cc_productos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JButton();
        txtPrecio = new javax.swing.JTextField();
        btn_quitar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtMontototal = new javax.swing.JTextField();
        btn_limpiar = new javax.swing.JButton();
        lnl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Módulo de ventas - Bodega El Olivar");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(51, 153, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Panel de ventas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(204, 255, 204))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(204, 255, 204));
        jPanel1.setToolTipText("");
        jPanel1.setFocusable(false);
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_p.setBackground(new java.awt.Color(204, 255, 204));
        tabla_p.setForeground(new java.awt.Color(0, 102, 51));
        tabla_p.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Precio del producto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabla_p.setGridColor(new java.awt.Color(0, 204, 51));
        tabla_p.setRequestFocusEnabled(false);
        tabla_p.setSelectionBackground(new java.awt.Color(0, 204, 51));
        tabla_p.setSelectionForeground(new java.awt.Color(204, 255, 204));
        tabla_p.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabla_p.setShowGrid(true);
        scrll_tabla1.setViewportView(tabla_p);

        jPanel1.add(scrll_tabla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 570, 360));

        cc_productos.setBackground(new java.awt.Color(0, 153, 0));
        cc_productos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cc_productos.setForeground(new java.awt.Color(204, 255, 204));
        cc_productos.setToolTipText("");
        cc_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cc_productosActionPerformed(evt);
            }
        });
        jPanel1.add(cc_productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 280, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("Precio (S/.):");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 36, 80, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("Producto:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 60, -1));

        btn_agregar.setBackground(new java.awt.Color(0, 153, 0));
        btn_agregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_agregar.setForeground(new java.awt.Color(204, 255, 204));
        btn_agregar.setText("Agregar");
        btn_agregar.setToolTipText("Agrega un producto para efectuar la venta.");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 455, 90, -1));

        txtPrecio.setBackground(new java.awt.Color(204, 255, 204));
        txtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(0, 102, 51));
        txtPrecio.setToolTipText("El precio del producto seleccionado");
        txtPrecio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 110, -1));

        btn_quitar.setBackground(new java.awt.Color(0, 153, 0));
        btn_quitar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_quitar.setForeground(new java.awt.Color(204, 255, 204));
        btn_quitar.setText("Quitar ");
        btn_quitar.setToolTipText("Elimina una fila seleccionada de la tabla correspondiente.");
        btn_quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_quitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 455, 90, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("Monto total (S/.):");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 455, 120, -1));

        txtMontototal.setBackground(new java.awt.Color(204, 255, 204));
        txtMontototal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMontototal.setForeground(new java.awt.Color(0, 102, 51));
        txtMontototal.setToolTipText("El monto final es la suma de todos los productos ");
        jPanel1.add(txtMontototal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 455, 150, -1));

        btn_limpiar.setBackground(new java.awt.Color(0, 153, 0));
        btn_limpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_limpiar.setForeground(new java.awt.Color(204, 255, 204));
        btn_limpiar.setText("Limpiar");
        btn_limpiar.setToolTipText("Vacía toda la tabla.");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 455, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 620, 500));

        lnl_fondo.setBackground(new java.awt.Color(51, 153, 0));
        lnl_fondo.setForeground(new java.awt.Color(51, 153, 0));
        lnl_fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnl_fondo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lnl_fondo.setFocusCycleRoot(true);
        lnl_fondo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lnl_fondo.setIconTextGap(2);
        lnl_fondo.setOpaque(true);
        getContentPane().add(lnl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 680, 540));

        setSize(new java.awt.Dimension(661, 562));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        try {    
        DefaultTableModel modelo = (DefaultTableModel) tabla_p.getModel();     
        for (int i = modelo.getRowCount() - 1; i >= 0; i--) {
                modelo.removeRow(i);
        }    //si existen las filas o fila correspondientes, se procede a eliminar esa fila o todas las filas que existan
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "No se puede limpiar la tabla. Verifique que al menos exista una fila", "Error", JOptionPane.ERROR_MESSAGE);                    
           }
        cc_productos.repaint();
        cc_productos.revalidate();
    }//GEN-LAST:event_btn_limpiarActionPerformed
    private void btn_quitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitarActionPerformed
        try {    
        DefaultTableModel modelo = (DefaultTableModel) tabla_p.getModel();     
        int fila = tabla_p.getSelectedRow();
        modelo.removeRow(fila);    //si existe algún valor, se elimina este valor de la tabla
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "No se puede eliminar una fila. Verifique que lo haya seleccionado", "Error", JOptionPane.ERROR_MESSAGE);                    
           }
        cc_productos.repaint();
        cc_productos.revalidate();
    }//GEN-LAST:event_btn_quitarActionPerformed
    private void cc_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cc_productosActionPerformed
        bsd_inventario.actualizacion_productos_TR(cc_productos, txtPrecio);
    }//GEN-LAST:event_cc_productosActionPerformed
private double obtener_valor_en(JTable tabla, int fila, int columna) {
    Object val = tabla.getValueAt(fila, columna);
    if (val == null) return 0.0; //si es 0, solo devuelve 0, para que no se reemplace todo el rato 
    try {
        return Double.parseDouble(val.toString());
    } catch (Exception e) {  //y si existe excepción porque aún no se agrega nada, devuelve 0.0
        return 0.0;
    }
}
    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        try {    
        DefaultTableModel modelo = (DefaultTableModel) tabla_p.getModel();     
            String precio_del_producto = txtPrecio.getText();
            String producto = cc_productos.getSelectedItem().toString();
            Object[] tabla_cmp_fila = {producto, precio_del_producto};
            modelo.addRow(tabla_cmp_fila);    //si existe algún valor, se agrega este valor a la tabla
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "No se puede agregar un valor.", "Error", JOptionPane.ERROR_MESSAGE);                    
           }
        cc_productos.repaint();
        cc_productos.revalidate();
    }//GEN-LAST:event_btn_agregarActionPerformed
    public void sumarxcolumna() {
       double sum = 0.0;  //esta función permite sumar desde la segunda columna, para que nos de un total de lo que se va comprar
    for (int i = 0; i < tabla_p.getRowCount(); i++) {
        sum += obtener_valor_en(tabla_p, i, 1); // 1 = columna del precio del producto 
    }
        txtMontototal.setText(String.valueOf(sum));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JF_Ventas(inicio).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_quitar;
    private javax.swing.JComboBox<String> cc_productos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lnl_fondo;
    private javax.swing.JScrollPane scrll_tabla1;
    private javax.swing.JTable tabla_p;
    private javax.swing.JTextField txtMontototal;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
